[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  # Set the Hugo version
  HUGO_VERSION = "0.139.2"
  NODE_VERSION = "lts/*"

# Set environment variables
[context.production.environment]
  HUGO_ENVIRONMENT = "production"
  GO_VERSION = "1.23"
  HUGO_BASEURL = "https://docs.ksctl.com/"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
