[build]
  # Set the Hugo version
  HUGO_VERSION = "0.139.2"
  
  # Build command
  command = """
    sudo snap install dart-sass && 
    npm install -D postcss postcss-cli autoprefixer hugo-extended && 
    hugo --gc --minify
  """
  
  # Publish directory
  publish = "public"

# Set environment variables
[context.production.environment]
  HUGO_ENVIRONMENT = "production"
  HUGO_ENV = "production"

# Node.js version configuration
[build.environment]
  NODE_VERSION = "lts/*"

# Optional: Add headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Optional: Redirects (if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
